apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autosetup.fullname" . }}
  labels:
    {{- include "autosetup.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "autosetup.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}          
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "autosetup.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.portContainer }}
          envFrom:
            - secretRef:
                name: autosetup-beta-secret
          env:
            - name: SPRING_JPA_HIBERNATE_DDL-AUTO
              value: "update"
            - name: VAULT_TIMEOUT
              value: "30"
            - name: RETRY_MAXATTEMPTS
              value: "3"
            - name: RETRY_BACKOFFDELAY
              value: "500"                  
            #- name: MAIL_SMTP_HOST
            #  value: "mailauth.telekom.de"
            #- name: MAIL_SMTP_PORT
            #  value: "587"
            #- name: MAIL_FROM_ADDRESS
            #  value: "Auto Setup technical team<tech@telekom.de>"
            #- name: MAIL_REPLYTO_ADDRESS
            #  value: "sachin.argade@t-systems.com,ADITYA.GAJBHIYE@t-systems.com"
            #- name: MAIL_SMTP_STARTTLS_ENABLE
            #  value: "true"
            #- name: MAIL_SMTP_AUTH
            #  value: "true"


          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
