apiVersion: v1
kind: Service
metadata:
  name: {{ include "autosetup.fullname" . }}
  labels:
    {{- include "autosetup.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    {{- include "autosetup.selectorLabels" . | nindent 4 }}
